version: "3.9"

services:
  app:
    build:
      context: .
    container_name: app
    # uwsgi --http:9000 --module diep_project.wsgi" 0.0.0.0:5000
    # uwsgi --socket :9000 --workers 4 --master --enable-threads --module diep_project.wsgi
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate
             uwsgi --http :8000 --module diep_project.wsgi"
    restart: always
    volumes:
      - static-data:/vol/web
    expose:
      - "8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    container_name: proxy
    # command: >
    #   sh -c "envsubst < /etc/nginx/default.conf.tpl > /etc/nginx/conf.d/default.conf
    #          nginx -g 'daemon off;'"
    links:
      - app:app
    depends_on:
      - app
    ports:
      - 80:80
      # - 443:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data: