# Generated by Django 4.0 on 2022-02-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['number'], 'verbose_name_plural': '03. Slide hình ảnh'},
        ),
        migrations.AddField(
            model_name='slide',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
    ]
