# Generated by Django 4.0 on 2022-02-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0003_ingredient_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['number'], 'verbose_name_plural': '05. Thành phần'},
        ),
    ]
