# Generated by Django 4.0 on 2022-02-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0004_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created'], 'verbose_name_plural': '12. Sản phẩm'},
        ),
    ]
