# Generated by Django 4.0 on 2022-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontent',
            name='counterfeiting_photo_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh chống hàng giả (Mobile)'),
        ),
    ]
